using System.Text.Json;

namespace GameServerApp.Plugins.FiveM;

public static class FiveMServerConfig
{
    private static readonly string[] DefaultResources =
    [
        "mapmanager",
        "chat",
        "spawnmanager",
        "sessionmanager",
        "basic-gamemode",
        "hardcap",
        "baseevents"
    ];

    public static void Write(string path, Dictionary<string, object> configValues)
    {
        using var writer = new StreamWriter(path);

        writer.WriteLine("# FiveM Server Configuration");
        writer.WriteLine("# Generated by Game Server Manager");
        writer.WriteLine();

        foreach (var (key, value) in configValues)
        {
            if (key == "server-port") continue;

            var strValue = value switch
            {
                bool b => b ? "1" : "0",
                JsonElement je => je.ValueKind switch
                {
                    JsonValueKind.True => "1",
                    JsonValueKind.False => "0",
                    JsonValueKind.Number => je.GetRawText(),
                    _ => je.GetString() ?? ""
                },
                _ => value.ToString() ?? ""
            };

            if (string.IsNullOrEmpty(strValue) && key != "sv_enforceGameBuild") continue;

            if (key.StartsWith("sets ") || key.StartsWith("set "))
            {
                writer.WriteLine($"{key} \"{strValue}\"");
            }
            else if (key == "sv_scriptHookAllowed")
            {
                writer.WriteLine($"{key} {strValue}");
            }
            else if (key == "sv_maxclients")
            {
                writer.WriteLine($"{key} {strValue}");
            }
            else if (key == "sv_enforceGameBuild" && !string.IsNullOrEmpty(strValue))
            {
                writer.WriteLine($"{key} {strValue}");
            }
            else if (key == "sv_enforceGameBuild")
            {
                continue;
            }
            else
            {
                writer.WriteLine($"{key} \"{strValue}\"");
            }
        }

        writer.WriteLine();
        writer.WriteLine("# Default resources");
        foreach (var resource in DefaultResources)
        {
            writer.WriteLine($"ensure {resource}");
        }
    }

    public static Dictionary<string, object> Read(string path)
    {
        var result = new Dictionary<string, object>();
        if (!File.Exists(path)) return result;

        foreach (var line in File.ReadAllLines(path))
        {
            var trimmed = line.Trim();
            if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith('#'))
                continue;

            if (trimmed.StartsWith("ensure") || trimmed.StartsWith("start") || trimmed.StartsWith("stop"))
                continue;

            if (trimmed.StartsWith("sets ") || trimmed.StartsWith("set "))
            {
                var parts = SplitConfigLine(trimmed);
                if (parts is { Key: not null, Value: not null })
                    result[parts.Key] = parts.Value;
                continue;
            }

            var kv = SplitSimpleConfigLine(trimmed);
            if (kv is { Key: not null, Value: not null })
            {
                if (kv.Key is "sv_maxclients" or "server-port" &&
                    int.TryParse(kv.Value, out var intVal))
                {
                    result[kv.Key] = intVal;
                }
                else if (kv.Key == "sv_scriptHookAllowed")
                {
                    result[kv.Key] = kv.Value == "1";
                }
                else
                {
                    result[kv.Key] = kv.Value;
                }
            }
        }

        return result;
    }

    private static (string? Key, string? Value) SplitConfigLine(string line)
    {
        var firstSpace = line.IndexOf(' ');
        if (firstSpace < 0) return (null, null);

        var secondSpace = line.IndexOf(' ', firstSpace + 1);
        if (secondSpace < 0) return (null, null);

        var key = line[..(secondSpace)].Trim();
        var value = line[(secondSpace + 1)..].Trim().Trim('"');
        return (key, value);
    }

    private static (string? Key, string? Value) SplitSimpleConfigLine(string line)
    {
        var spaceIndex = line.IndexOf(' ');
        if (spaceIndex < 0) return (line, "");

        var key = line[..spaceIndex].Trim();
        var value = line[(spaceIndex + 1)..].Trim().Trim('"');
        return (key, value);
    }
}
