namespace GameServerApp.Plugins.Minecraft;

public static class MinecraftServerProperties
{
    public static Dictionary<string, object> Read(string filePath)
    {
        var result = new Dictionary<string, object>();

        if (!File.Exists(filePath))
            return result;

        foreach (var line in File.ReadAllLines(filePath))
        {
            var trimmed = line.Trim();
            if (string.IsNullOrEmpty(trimmed) || trimmed.StartsWith('#'))
                continue;

            var eqIndex = trimmed.IndexOf('=');
            if (eqIndex < 0)
                continue;

            var key = trimmed[..eqIndex].Trim();
            var value = trimmed[(eqIndex + 1)..].Trim();

            result[key] = value;
        }

        return result;
    }

    public static void Write(string filePath, Dictionary<string, object> properties)
    {
        var lines = new List<string>
        {
            "#Minecraft server properties",
            $"#Generated by Game Server Manager on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC"
        };

        foreach (var (key, value) in properties.OrderBy(p => p.Key))
        {
            var strValue = value switch
            {
                bool b => b.ToString().ToLowerInvariant(),
                _ => value?.ToString() ?? ""
            };
            lines.Add($"{key}={strValue}");
        }

        File.WriteAllLines(filePath, lines);
    }
}
